version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    target-branch: "master"
    # Only do security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    target-branch: "master"
    # Only do security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    target-branch: "master"
    # Only do security updates
    open-pull-requests-limit: 0
