// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationModal: typeof import('./src/components/modals/ConfirmationModal.vue')['default']
    ScreenSaver: typeof import('./src/components/screensaver/ScreenSaver.vue')['default']
    ServerStatus: typeof import('./src/components/status/serverStatus.vue')['default']
    TeamCard: typeof import('./src/components/teams/TeamCard.vue')['default']
  }
}

export { }
