/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationModal: typeof import('./src/components/modals/ConfirmationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenSaver: typeof import('./src/components/screensaver/ScreenSaver.vue')['default']
    ServerStatus: typeof import('./src/components/status/serverStatus.vue')['default']
    TeamCard: typeof import('./src/components/teams/TeamCard.vue')['default']
  }
}
